from flask import Flask, request, jsonify
import yt_dlp
import os
import json

app = Flask(__name__)

COOKIES_PATH = "/tmp/cookies.txt"

# 🔥 الكوكيز Netscape
COOKIES_CONTENT = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	FALSE	0	PREF	hl=en&tz=UTC
.youtube.com	TRUE	/	TRUE	0	SOCS	CAI
.youtube.com	TRUE	/	TRUE	1789290644	__Secure-YNID	16.YT=W40nxJsPVBjJaDWH08ynJPJpD9wcihOD_hilC71JneGR9tinDFyBO47y1F41VgFq83VcjoF6B0NBg-5L9gCby_NewAOxsio-wBJRE51HuE3iZzfV2vL1Kw77zgRcL4oK0gdxOFQ2FtV1AQ6WCMlkmhv0sBx7-LVmDUJPBKrmFvBfhWiQ6l89bAbPZd7G4MVv8UCluT8R32w1eej-CKO9MJco-Ml57NRywHCPNxwycDO6RGBVnch7rxFGx8UVk7zpBnTSETfY5qiJ-I4BnclAZ36-hLRDm3ODBaspSN-O920FeRlg1qB00JVoLviyuRtgQluOE50j2B6NQ1QJWPYVVA
.youtube.com	TRUE	/	TRUE	1773740444	GPS	1
.youtube.com	TRUE	/	TRUE	0	YSC	Mmd2STEsJ4o
.youtube.com	TRUE	/	TRUE	1789290644	__Secure-ROLLOUT_TOKEN	CJ-8-ujxr9vhfRC8j9Ouy6aTAxi8j9Ouy6aTAw%3D%3D
.youtube.com	TRUE	/	TRUE	1789290644	VISITOR_INFO1_LIVE	wcl_1SERt3g
.youtube.com	TRUE	/	TRUE	1789290644	VISITOR_PRIVACY_METADATA	CgJFRxIEGgAgSw%3D%3D

"""

def ensure_cookies():
    """إنشاء ملف الكوكيز داخل /tmp"""
    if not os.path.exists(COOKIES_PATH):
        with open(COOKIES_PATH, "w") as f:
            f.write(COOKIES_CONTENT)

def extract_full_info(url):
    ensure_cookies()

    ydl_opts = {
        "cookiefile": COOKIES_PATH,
        "quiet": True,
        "no_warnings": True,
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)

    return info


@app.route("/")
def home():
    return jsonify({
        "status": "ok",
        "usage": "/info?url=VIDEO_URL"
    })


@app.route("/info")
def info():
    url = request.args.get("url")

    if not url:
        return jsonify({"error": "يرجى ارسال رابط الفيديو"}), 400

    try:
        data = extract_full_info(url)

        # 🔥 تحويل آمن JSON كامل
        return app.response_class(
            response=json.dumps(data, ensure_ascii=False, default=str),
            status=200,
            mimetype='application/json'
        )

    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
