# Developer: محمود عادل الغريب

from flask import Flask, request, jsonify
import yt_dlp
import tempfile

app = Flask(__name__)

# 🟢 هنا تحط محتوى الكوكيز بين Triple Quotes
COOKIES = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	FALSE	0	PREF	hl=en&tz=UTC
.youtube.com	TRUE	/	TRUE	0	SOCS	CAI
.youtube.com	TRUE	/	TRUE	1787080733	__Secure-YNID	16.YT=03x6dPNvIK4Jd5TRgXJQrsboNok_VsdjX0JFnDLvMTgDOk-XjFL4RBOjJmF8U1Z6h_UCQ1bgvJWwT_KplwR5A0m9nglhd_Ojvm0s2AKx6QEJxhTONxf98P4Cj2AXwbY_w42cHGIRj2SzW7XaeJNqMXad2IzgivkdN5sPI55kriSho_4fxhSpkshaKSqYs7B-ZMK4YkdrmtoiTnAogqWMf1NZ3sBYR7g1T3Jd-cVX0hFic7xg5L_NrrwONjO5Sb09pXCCM_R8zm23fdGIgce65m9cE9BlhLSej1njUM4ar9l00Em-ayc1zmZveLDIO88w9Us5RFcZ7L9S2PSmxLZYWA
.youtube.com	TRUE	/	TRUE	1771530533	GPS	1
.youtube.com	TRUE	/	TRUE	0	YSC	eRAJBDvU3Bk
.youtube.com	TRUE	/	TRUE	1787080751	VISITOR_INFO1_LIVE	K_dYbujjQf4
.youtube.com	TRUE	/	TRUE	1787080751	VISITOR_PRIVACY_METADATA	CgJFRxIEGgAgGQ%3D%3D
.youtube.com	TRUE	/	TRUE	1787080751	__Secure-ROLLOUT_TOKEN	CIrs5qvwucSDvAEQ2pKC56LmkgMYxOne76LmkgM%3D
"""

@app.route("/info")
def video_info():
    url = request.args.get("url")
    if not url:
        return jsonify({"error": "Missing url parameter"}), 400

    ydl_opts = {
        "quiet": True,
        "skip_download": True,
        "nocheckcertificate": True,
        "geo_bypass": True,
        "force_ipv4": True,
        "extractor_args": {
            "youtube": {"player_client": ["android", "web"]}
        }
    }

    # نكتب الكوكيز في ملف مؤقت عشان yt-dlp يقرأه
    with tempfile.NamedTemporaryFile(mode="w+", delete=False) as tmp:
        tmp.write(COOKIES)
        tmp.flush()
        ydl_opts["cookiefile"] = tmp.name

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

            downloads = []
            for f in info.get("formats", []):
                if f.get("url") and f.get("vcodec") != "none":
                    downloads.append({
                        "format_id": f.get("format_id"),
                        "ext": f.get("ext"),
                        "resolution": f.get("resolution") or f.get("format_note"),
                        "filesize_mb": round(f.get("filesize", 0)/(1024*1024),2) if f.get("filesize") else None,
                        "download_url": f.get("url")
                    })

            return jsonify({
                "title": info.get("title"),
                "uploader": info.get("uploader"),
                "duration_seconds": info.get("duration"),
                "views": info.get("view_count"),
                "thumbnail": info.get("thumbnail"),
                "downloads": downloads
            })
    except Exception as e:
        return jsonify({"error": str(e)}), 500
