from flask import Flask, request, jsonify
import yt_dlp

app = Flask(__name__)

COOKIES = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com  TRUE    /   TRUE    1789243250  VISITOR_PRIVACY_METADATA    CgJJURIEGgAgQA%3D%3D
.youtube.com    TRUE    /   FALSE   1773691261  ST-3opvp5   session_logininfo=AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg%3AQUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
.youtube.com    TRUE    /   FALSE   1773691257  ST-xuwub9   session_logininfo=AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg%3AQUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
#HttpOnly_.youtube.com  TRUE    /   TRUE    1806791629  __Secure-3PSID  g.a0007QhXAmr1U3Q0NYY6kiwRF6Ztgk0VNzjq1xBJegptu8fXqGDNrNNdw8-_Yq29J9AzwpXEIQACgYKARUSARcSFQHGX2Mi8N7wcvEp6v6CqYZVVwiTJRoVAUF8yKr_-U0BgYLjSzmn9lIaMMah0076
#HttpOnly_.youtube.com  TRUE    /   TRUE    1770056815  GPS 1
.youtube.com    TRUE    /   FALSE   1805227252  SIDCC   AKEyXzWK0yKCI6TuBpT-Vs_PHa3G9140XMYPVzwtLAKInLD1PH71yR-kFzAMdHPPBfW3QHto
#HttpOnly_.youtube.com  TRUE    /   TRUE    1773777662  YSC 8wneiIw8M20
.youtube.com    TRUE    /   FALSE   1806791629  SID g.a0007QhXAmr1U3Q0NYY6kiwRF6Ztgk0VNzjq1xBJegptu8fXqGDNZHhDufSo41hEH8FgMsEqOQACgYKAVwSARcSFQHGX2MiqE3aDg4KXUNtZ1PlSj_9xhoVAUF8yKp763S4jP2exW46cbDOzEa-0076
#HttpOnly_.youtube.com  TRUE    /   TRUE    1805227239  __Secure-1PSIDTS    sidts-CjUBBj1CYrLnGexOBm6LJ3pvvwvJU7Xoc7Rc4b9ldIlN4l7395uvTmzgESlOx4niwJZ_k3N4TxAA
.youtube.com    TRUE    /   TRUE    1806791629  SAPISID OT-WlM8mP0Tw5Ofm/AWO2s_IZo_5iGqPJS
#HttpOnly_.youtube.com  TRUE    /   TRUE    1805227252  __Secure-1PSIDCC    AKEyXzV6qSumFofyLP93Jb7ZaiY5DBp1x35ZhCXJnEuvGrdvkO023PkP3G9ew6zUGHHp9V8geQ
.youtube.com    TRUE    /   FALSE   1771015075  ST-hcbf8d   session_logininfo=AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg%3AQUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
#HttpOnly_.youtube.com  TRUE    /   TRUE    1806791629  SSID    Aj1Lhld2qNo_RLaOd
.youtube.com    TRUE    /   FALSE   1770055130  ST-uwicob   session_logininfo=AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg%3AQUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
.youtube.com    TRUE    /   FALSE   1773691257  ST-tladcw   session_logininfo=AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg%3AQUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
.youtube.com    TRUE    /   TRUE    1806791629  __Secure-1PAPISID   OT-WlM8mP0Tw5Ofm/AWO2s_IZo_5iGqPJS
#HttpOnly_.youtube.com  TRUE    /   TRUE    1806791629  __Secure-1PSID  g.a0007QhXAmr1U3Q0NYY6kiwRF6Ztgk0VNzjq1xBJegptu8fXqGDNYFXXEuWGSkkmWUIgouC61gACgYKAYsSARcSFQHGX2MiZzTR5AyMO8z7Tc9yQpsKQRoVAUF8yKok8GWAJkjz2ljOve_B_lQ70076
.youtube.com    TRUE    /   TRUE    1806791629  __Secure-3PAPISID   OT-WlM8mP0Tw5Ofm/AWO2s_IZo_5iGqPJS
#HttpOnly_.youtube.com  TRUE    /   TRUE    1805227252  __Secure-3PSIDCC    AKEyXzWc4NuSmGCruGtE2J-HP92f1WDLfLKruZ15VNi_bWUkRTBnyqX1KdVbVUAAeGrNMEf0mQ
#HttpOnly_.youtube.com  TRUE    /   TRUE    1805227239  __Secure-3PSIDTS    sidts-CjUBBj1CYrLnGexOBm6LJ3pvvwvJU7Xoc7Rc4b9ldIlN4l7395uvTmzgESlOx4niwJZ_k3N4TxAA
#HttpOnly_.youtube.com  TRUE    /   TRUE    1789243235  __Secure-YNID   16.YT=4RcwJxhEnTXZv56PlMj2jAQtFrj6tIHyNll2-Ml16DSf5xsmdhr7IxJKnVRhs9KdgoldPv_C3AdR2xIKICBw6_MfYm47n1JHdeb1oNlO4Fl7QB0xv-PfDWum2bykkXQhKhT0u84OMrUftHMTGJT2GKA-no5KtYUu7QsXnzm0J4lfPIRYe2BGXyAKDl_bE9l0H9nAhhGPG0Rxb1BZqnkplObiKLUa7Zx9yn36R55qmK9RbB6BCH6DQzuLpMbkpjpWfVTRgp3nO8-JcoBzXhmfbkPOXThU6aBvkEOSmC_etJzlecdfZXCyaPmtqAZWsbu19QqTkcsDBkSzfGhPVAxDRQ
.youtube.com    TRUE    /   FALSE   1806791629  APISID  PCAYqwFbzvJxDC-f/A_Ho6EIwusylCX5Us
#HttpOnly_.youtube.com  TRUE    /   FALSE   1806791629  HSID    AiDCODsYPTH3kAWVS
#HttpOnly_.youtube.com  TRUE    /   TRUE    1804615117  LOGIN_INFO  AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg:QUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
.youtube.com    TRUE    /   TRUE    1808251252  PREF    tz=Asia.Baghdad
.youtube.com    TRUE    /   FALSE   1773691240  ST-1supwba  session_logininfo=AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg%3AQUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
.youtube.com    TRUE    /   FALSE   1770055126  ST-l3hjtt   session_logininfo=AFmmF2swRQIgZ-Jonb5CrcwKOCHmao2fshO4qAxnmS2b0mwP0U6anD4CIQDwIUH6abJPbFZYz9_C8LF-7jK9Ours09A6hHTuS6skNg%3AQUQ3MjNmeUI2U2dCbHhORUVCc2NKT0syUjJKT1VmNUlHR0RCSlBxbzlnLXhUSmdIYVh4N3dGNWZaQ1ZwOWEwdXBONlZuY3pjbEZ0MlJHTWVSYXhTMVBmOWVMbERuTzU2WTVrYk1fb2pxQTlpWG5waGoydGJhWEc2aGlLaTQwcXowT0VNdVBQc3E1Z0VqSUEwdF9YbkdzdHhyRU1yTEF2SlVR
#HttpOnly_.youtube.com  TRUE    /   TRUE    1789243250  VISITOR_INFO1_LIVE  dlILqF2hu44
"""

cookie_path = "/tmp/cookies.txt"

with open(cookie_path, "w") as f:
    f.write(COOKIES.strip())


@app.route("/info")
def info():

    url = request.args.get("url")

    if not url:
        return jsonify({"error": "ضع رابط الفيديو"}), 400

    ydl_opts = {
        "cookiefile": cookie_path,
        "quiet": True,
        "skip_download": True
    }

    try:

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            data = ydl.extract_info(url, download=False)

        video_formats = []
        audio_formats = []

        for f in data.get("formats", []):

            item = {
                "itag": f.get("format_id"),
                "quality": f.get("format_note"),
                "resolution": f"{f.get('width')}x{f.get('height')}" if f.get("width") else None,
                "fps": f.get("fps"),
                "ext": f.get("ext"),
                "filesize": f.get("filesize"),
                "bitrate": f.get("tbr"),
                "url": f.get("url")
            }

            if f.get("vcodec") != "none":
                video_formats.append(item)

            if f.get("acodec") != "none" and f.get("vcodec") == "none":
                audio_formats.append(item)

        response = {
            "title": data.get("title"),
            "description": data.get("description"),
            "duration": data.get("duration"),
            "view_count": data.get("view_count"),
            "like_count": data.get("like_count"),
            "upload_date": data.get("upload_date"),
            "channel": data.get("channel"),
            "channel_url": data.get("channel_url"),
            "uploader": data.get("uploader"),
            "thumbnail": data.get("thumbnail"),
            "tags": data.get("tags"),
            "video_formats": video_formats,
            "audio_formats": audio_formats
        }

        return jsonify(response)

    except Exception as e:
        return jsonify({"error": str(e)})


@app.route("/")
def home():
    return {"message": "YouTube Full Info API يعمل"}


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
